import type { Metadata } from "next";
import "@atomos_tech/genesis/style";
import "./globals.css";

export const metadata: Metadata = {
  title: "Genesis Date Picker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="theme-primary">{children}</div>
      </body>
    </html>
  );
}
